# Generated by Django 6.0.7 on 2026-08-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_task_manager', '0002_alter_worker_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
