# Generated by Django 6.0.5 on 2026-08-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_task_manager', '0005_alter_position_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['name'], 'permissions': [('complete_task', 'Can complete task')]},
        ),
    ]
