# Generated by Django 6.0.7 on 2026-08-10 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_task_manager', '0006_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
