# Generated by Django 6.0.5 on 2026-08-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_task_manager', '0007_worker_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
