# Generated by Django 6.0.5 on 2026-08-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_task_manager', '0008_tasktype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
